name: Deploy to Firebase Hosting
'on':
  push:
    branches:
      - gh-pages
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_OJT_ONLINE }}'
          channelId: live
          projectId: ojt-online
